name: Java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  verify:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true -Dgpg.skip verify

  test:

    timeout-minutes: 30
    needs: verify
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
        docker-img:
          - docker.io/arangodb/arangodb:3.6.11
          - docker.io/arangodb/enterprise:3.6.11
          - docker.io/arangodb/arangodb:3.7.6
          - docker.io/arangodb/enterprise:3.7.6

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
      - name: Info
        run: mvn -version
      - name: Configure reuse containers
        run: echo "testcontainers.reuse.enable=true" >> ~/.testcontainers.properties
      - name: Test
        run: mvn -e --no-transfer-progress test -DexcludedGroups="resiliency" -Dtest.docker.image="${{matrix.docker-img}}" -Darango.license.key="$ARANGO_LICENSE_KEY" -Dtestcontainers.reuse.enable=true -Dtest.serde.failOnUnknownProperties=true
        env:
          ARANGO_LICENSE_KEY: ${{secrets.ARANGO_LICENSE_KEY}}
      - name: Uploading containers logs
        uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        with:
          name: containers-logs
          path: arangodb-java-reactive-driver/log/deployments
